services:
  telebot:
    image: telebot:v0.1.0
    build:
      context: ../server
      args:
        STORAGE_HOST: ${STORAGE_HOST}
        STORAGE_DB: ${STORAGE_DB}
        STORAGE_USER: ${STORAGE_USER}
        STORAGE_PASSWORD: ${STORAGE_PASSWORD}
    restart: unless-stopped
    networks:
      - "kafka-network"
      - "storage-network"
  greeter:
    image: greeter:0.0.0
    build: ../greeter
    restart: unless-stopped
    networks:
      - "kafka-network"
networks:
  kafka-network:
    external: true
  storage-network:
    external: true