services:
  telebot:
    image: telebot:v2.0.3
    build:
      context: ../server
    restart: unless-stopped
    networks:
      - "kafka-network"
      - "storage-network"
    volumes:
      - ${data_folder}:/var/lib/telebot
      - ${config_path}:/config.yml
  greeter:
    image: greeter:v2.0.3
    build: ../greeter
    restart: unless-stopped
    networks:
      - "kafka-network"
    volumes:
      - ${data_folder}:/var/lib/telebot
networks:
  kafka-network:
    external: true
  storage-network:
    external: true