services:
  telebot:
    image: telebot:v2.0.5
    build:
      context: ../server
    restart: unless-stopped
    networks:
      - "kafka-network"
      - "storage-network"
    volumes:
      - ${data_folder}:/var/lib/telebot
      - ${config_path}:/config.yml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  greeter:
    image: greeter:v2.0.6
    build: ../greeter
    restart: unless-stopped
    networks:
      - "kafka-network"
    volumes:
      - ${data_folder}:/var/lib/telebot
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
networks:
  kafka-network:
    external: true
  storage-network:
    external: true